#!/bin/bash
#SBATCH --job-name=mace_Na3PO4_1000K
#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH --partition=a40
#SBATCH --time=8:00:00
#SBATCH --export=ALL
#SBATCH --output=%x-%j.out
#SBATCH --error=%x-%j.err
#SBATCH --mail-user=luis.schmidt@tum.de
#SBATCH --mail-type=END,FAIL,TIME_LIMIT

# Environment setup
module purge
module load python/3.12-base
module load cuda/12.9.1
module load openmpi/4.1.8-gcc11.5.0-cuda12.9

export LD_LIBRARY_PATH=/apps/python/3.12-miniforge/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/home/atuin/b299bb/TheoFEM/Modules/lammps/build-mliap:$LD_LIBRARY_PATH

source /home/atuin/b299bb/TheoFEM/Environments/theofem312/bin/activate

export LAMMPS=/home/atuin/b299bb/TheoFEM/Modules/lammps/build-mliap/bin/lmp

srun $LAMMPS -k on g 1 -sf kk -pk kokkos newton on neigh half -in simulation1000K.lmp
